### ISSUE TITLE
License justification

### ISSUE THREAD

**Issue by erictsai1208** [UBC-MDS/sentimentanalyzerR#39]

**Comment by erictsai1208** [comment]
https://github.com/UBC-MDS/py-sentimentanalyzer/issues/54

**Comment by zchen156** [comment]
For our R package, we also think MIT license is suitable. Because it is a well-known and respected open-source license in the industry. By selecting the MIT license, we can guarantee that our sentiment analyzer package is widely available and may be used by a large group of users. The MIT license's permissiveness is one of its main advantages. The package may be used, altered, and distributed as long as users include a copy of the licence along with the package. Users no longer need to be concerned about license limitations when utilizing and integrating our sentiment analysis software into their own projects thanks to this. The simplicity of the MIT licence is another benefit. A common option for open-source package, the license is brief and simple to read. By employing our sentiment analyzer package, users may quickly and simply understand their rights and obligations without needing to wade through complicated legalese. It is also simple to combine our sentiment analyzer package with other open-source packages because the MIT licence is compatible with a wide range of other open-source licences. This is crucial because it enables users to improve and add to our package, fostering the development of a healthy ecosystem of tools and software that can be used to a variety of issues.
